//! YAML serializers for OpenAPI 3.1 and AsyncAPI 2.x.

use crate::specgen::coverage::SpecSource;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpenApiDoc {
    pub openapi: String,
    pub info: OpenApiInfo,
    pub servers: Vec<OpenApiServer>,
    pub paths: BTreeMap<String, OpenApiPathItem>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpenApiInfo {
    pub title: String,
    pub version: String,
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpenApiServer {
    pub url: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OpenApiPathItem {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub get: Option<OpenApiOperation>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub post: Option<OpenApiOperation>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub put: Option<OpenApiOperation>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delete: Option<OpenApiOperation>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub patch: Option<OpenApiOperation>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpenApiOperation {
    /// camelCase on the wire so the serialized YAML/JSON matches
    /// the OpenAPI 3.1 schema and the LLM validation regex
    /// (`^[a-z][a-zA-Z0-9]+$`). The Rust-side field stays
    /// snake_case for idiomatic access.
    #[serde(rename = "operationId")]
    pub operation_id: String,
    pub summary: String,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub parameters: Vec<OpenApiParameter>,
    pub responses: BTreeMap<String, OpenApiResponse>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpenApiParameter {
    pub name: String,
    #[serde(rename = "in")]
    pub location: String,
    pub required: bool,
    pub schema: OpenApiSchema,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpenApiResponse {
    pub description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<BTreeMap<String, OpenApiMediaType>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpenApiMediaType {
    pub schema: OpenApiSchema,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub examples: Option<BTreeMap<String, OpenApiExample>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpenApiExample {
    pub value: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpenApiSchema {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub schema_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub properties: Option<BTreeMap<String, OpenApiSchema>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub example: Option<serde_json::Value>,
}

pub fn render_openapi(
    title: &str,
    base_url: &str,
    paths: BTreeMap<String, OpenApiPathItem>,
    source: SpecSource,
) -> String {
    let doc = OpenApiDoc {
        openapi: "3.1.0".into(),
        info: OpenApiInfo {
            title: title.to_string(),
            version: "1.0.0".into(),
            description: format!("Generated by ProxyBot specgen (source: {:?})", source),
        },
        servers: vec![OpenApiServer { url: base_url.to_string() }],
        paths,
    };
    serde_yaml::to_string(&doc).expect("OpenAPI doc must serialize")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::specgen::extract::template_path;

    fn make_op(id: &str) -> OpenApiOperation {
        OpenApiOperation {
            operation_id: id.into(),
            summary: format!("Test {}", id),
            tags: vec!["test".into()],
            parameters: vec![],
            responses: BTreeMap::new(),
        }
    }

    #[test]
    fn renders_minimal_openapi() {
        let mut paths = BTreeMap::new();
        let tpl = template_path("/api/users/1").template;
        paths.insert(
            tpl,
            OpenApiPathItem {
                get: Some(make_op("getUser")),
                ..Default::default()
            },
        );
        let yaml = render_openapi("Test API", "https://example.com", paths, SpecSource::Heuristic);
        assert!(yaml.contains("openapi: 3.1.0"));
        assert!(yaml.contains("title: Test API"));
        assert!(yaml.contains("/api/users/{usersId}"));
        assert!(yaml.contains("getUser"));
    }

    #[test]
    fn openapi_doc_parses_back() {
        let mut paths = BTreeMap::new();
        paths.insert(
            "/x".into(),
            OpenApiPathItem {
                get: Some(make_op("getX")),
                ..Default::default()
            },
        );
        let yaml = render_openapi("x", "https://x", paths, SpecSource::Llm);
        let doc: OpenApiDoc = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(doc.openapi, "3.1.0");
        assert!(doc.paths["/x"].get.is_some());
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AsyncApiDoc {
    pub asyncapi: String,
    pub info: OpenApiInfo,
    pub servers: Vec<OpenApiServer>,
    pub channels: BTreeMap<String, AsyncApiChannel>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AsyncApiChannel {
    pub description: String,
    pub subscribe: Option<AsyncApiMessage>,
    pub publish: Option<AsyncApiMessage>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AsyncApiMessage {
    pub payload: OpenApiSchema,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub examples: Option<Vec<AsyncApiExample>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AsyncApiExample {
    pub name: String,
    pub payload: serde_json::Value,
}

pub fn render_asyncapi(
    title: &str,
    base_url: &str,
    channels: BTreeMap<String, AsyncApiChannel>,
) -> String {
    let doc = AsyncApiDoc {
        asyncapi: "2.6.0".into(),
        info: OpenApiInfo {
            title: title.to_string(),
            version: "1.0.0".into(),
            description: "Generated by ProxyBot specgen".into(),
        },
        servers: vec![OpenApiServer { url: base_url.to_string() }],
        channels,
    };
    serde_yaml::to_string(&doc).expect("AsyncAPI doc must serialize")
}

#[cfg(test)]
mod asyncapi_tests {
    use super::*;

    #[test]
    fn renders_minimal_asyncapi() {
        let mut channels = BTreeMap::new();
        channels.insert(
            "/ws/chat".to_string(),
            AsyncApiChannel {
                description: "Chat".into(),
                subscribe: Some(AsyncApiMessage {
                    payload: OpenApiSchema {
                        schema_type: Some("object".into()),
                        properties: None,
                        example: Some(serde_json::json!({"text": "hi"})),
                    },
                    examples: None,
                }),
                publish: None,
            },
        );
        let yaml = render_asyncapi("WS", "wss://x", channels);
        assert!(yaml.contains("asyncapi: 2.6.0"));
        assert!(yaml.contains("/ws/chat"));
        assert!(yaml.contains("text: hi"));
    }
}
