//! Rust-first desktop IPC contract generation.
//!
//! The first tracer slice covers Traffic and WebSocket calls/events. The
//! generated TypeScript is committed so frontend builds do not need Rust, and
//! CI regenerates it in check mode to catch drift.

use crate::normalize::{NormalizedRecord, TrafficPage};
use crate::proxy::WsFrameEvent;
use proxybot_core::desktop_contract::DesktopContractType;
use proxybot_core::{BreakpointTarget, InterceptedRequest, Rule, RuleAction, RulePattern, WsFrame};
use std::fmt::Write;

pub const TRAFFIC_COMMANDS: &[&str] = &[
    "evaluate_filter",
    "export_har",
    "get_traffic_page",
    "get_ws_frames",
    "list_filter_presets",
    "load_history",
    "save_har_file",
    "save_history",
];

pub const TRAFFIC_EVENTS: &[&str] = &["intercepted-request", "ws-frame:new"];

pub const RULE_COMMANDS: &[&str] = &[
    "delete_rule",
    "get_rules",
    "list_rule_files",
    "match_host",
    "reorder_rules",
    "save_rule",
];

/// Render the checked-in TypeScript contract deterministically.
pub fn render_typescript() -> String {
    let mut output = String::from(
        "// @generated by `pnpm contract:generate`; do not edit by hand.\n\n\
         export type JsonPrimitive = boolean | number | string | null;\n\
         export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };\n\n",
    );

    for declaration in [
        InterceptedRequest::type_script_declaration(),
        WsFrame::type_script_declaration(),
        WsFrameEvent::type_script_declaration(),
        NormalizedRecord::type_script_declaration(),
        TrafficPage::type_script_declaration(),
        BreakpointTarget::type_script_declaration(),
        RulePattern::type_script_declaration(),
        RuleAction::type_script_declaration(),
        Rule::type_script_declaration(),
    ] {
        output.push_str(&declaration);
        output.push('\n');
    }

    output.push_str(
        "export interface FilterPreset {\n\
         \x20 id: string;\n\
         \x20 name: string;\n\
         \x20 expr: string;\n\
         }\n\n\
         export interface DesktopCommands {\n\
         \x20 delete_rule: { args: { rule: Rule; filename: string }; result: undefined };\n\
         \x20 evaluate_filter: { args: { expr: string; request: InterceptedRequest }; result: boolean };\n\
         \x20 export_har: { args: { sessionName: string }; result: JsonValue };\n\
         \x20 get_traffic_page: { args: { page: number; pageSize: number }; result: TrafficPage };\n\
         \x20 get_rules: { args: { filename: string }; result: Rule[] };\n\
         \x20 get_ws_frames: { args: { requestId: string }; result: WsFrame[] };\n\
         \x20 list_filter_presets: { args: Record<string, never>; result: FilterPreset[] };\n\
         \x20 list_rule_files: { args: Record<string, never>; result: string[] };\n\
         \x20 load_history: { args: Record<string, never>; result: InterceptedRequest[] };\n\
         \x20 match_host: { args: { host: string; ip: string | null }; result: RuleAction | null };\n\
         \x20 reorder_rules: { args: { fromIndex: number; toIndex: number; filename: string }; result: undefined };\n\
         \x20 save_har_file: { args: { harJson: string; sessionName: string }; result: string };\n\
         \x20 save_history: { args: { requests: InterceptedRequest[] }; result: undefined };\n\
         \x20 save_rule: { args: { rule: Rule; filename: string; originalRule: Rule | null }; result: undefined };\n\
         }\n\n\
         export interface DesktopEvents {\n\
         \x20 \"intercepted-request\": InterceptedRequest;\n\
         \x20 \"ws-frame:new\": WsFrameEvent;\n\
         }\n\n",
    );

    let command_names = TRAFFIC_COMMANDS
        .iter()
        .chain(RULE_COMMANDS)
        .copied()
        .collect::<Vec<_>>();
    write!(
        output,
        "export const desktopCommandNames = {} as const;\n\
         export const desktopEventNames = {} as const;\n\
         export const unitCommandNames = [\"delete_rule\",\"reorder_rules\",\"save_history\",\"save_rule\"] as const;\n",
        json_string_array(&command_names),
        json_string_array(TRAFFIC_EVENTS),
    )
    .expect("writing to a String cannot fail");

    output
}

fn json_string_array(values: &[&str]) -> String {
    serde_json::to_string(values).expect("static string arrays always serialize")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renderer_is_deterministic_and_contains_the_tracer_slice() {
        let first = render_typescript();
        assert_eq!(first, render_typescript());
        assert!(first.contains("export interface InterceptedRequest"));
        assert!(first.contains("get_traffic_page"));
        assert!(first.contains("save_rule"));
        assert!(first.contains("export type RuleAction"));
        assert!(first.contains("\"ws-frame:new\""));
    }
}
