// Re-export proxybot-core types for shared use
pub use proxybot_core as core;

pub mod adb;
pub mod ai;
pub mod ai_pipeline;
pub mod alerts;
pub mod anomaly;
mod bootstrap;
pub mod cdp;
pub mod cert;
pub mod cert_server;
pub mod commands;
pub mod dag;
pub mod dashboard;
pub mod db;
pub mod deploy;
pub mod desktop_contract;
pub mod dns;
pub mod error;
pub mod filter;
pub mod frida;
pub mod generation;
pub mod graphql;
pub mod har;
pub mod history;
pub mod infer;
pub mod mcp;
pub mod metrics;
pub mod mockgen;
pub mod network;
pub mod normalize;
pub mod pf;
pub mod plugin;
pub mod protobuf;
pub mod proxy;
pub mod replay;
pub mod rules;
pub mod runtime_extensions;
pub mod scaffoldgen;
pub mod scripting;
pub mod ssl_bypass;
pub mod state;
pub mod state_machine;
pub mod topology;
pub mod transport;
pub mod tun;
pub mod vision;
pub mod vpn;
pub mod workspace;
pub mod ws_frames;
pub use bootstrap::{run, DESKTOP_COMMANDS};
// The desktop bootstrap is intentionally kept in one Module. Binaries and
// mobile entry points are thin Adapters that delegate to `run`.
